#!/usr/bin/env bash
# Assemble .env from the three source layers (later overrides earlier):
#   config.env    committed, non-secret config
#   .env.secrets  generated secrets   (minted by generate-env.sh if absent)
#   .env.local    optional API keys + per-developer overrides
# One-time migration: if .env.secrets is absent but a legacy flat .env exists,
# its secrets (and any non-empty optional keys) are lifted into the new layers so
# a RUNNING stack keeps its credentials. Never clobbers an existing .env.secrets.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}/../.." # repo root

CONFIG="config.env"
SECRETS=".env.secrets"
LOCAL=".env.local"
OUT=".env"
NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

SECRET_KEYS="POSTGRES_PASSWORD AUTHENTICATOR_PASSWORD DATABASE_URL PGRST_DB_URI \
ADAPTER_REGISTRY_DATABASE_URL JWT_SECRET ADAPTER_REGISTRY_SERVICE_TOKEN ANON_KEY \
SERVICE_ROLE_KEY KONG_PUBLIC_API_KEY KONG_SERVICE_API_KEY MINIO_ROOT_PASSWORD \
VAULT_ENC_KEY MONGO_INITDB_ROOT_PASSWORD LOG_STREAM_TOKEN"
OPTIONAL_KEYS="GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET GITHUB_CLIENT_ID \
GITHUB_CLIENT_SECRET FORTYTWO_CLIENT_ID FORTYTWO_CLIENT_SECRET SMTP_USER SMTP_PASS \
LLM_API_KEY GDPR_DELETION_WEBHOOK_URL GDPR_EXPORT_WEBHOOK_URL SONAR_TOKEN"

[ -f "$CONFIG" ] || {
  echo "Error: $CONFIG missing (the committed config layer)." >&2
  exit 1
}

# ── 1. secrets layer ─────────────────────────────────────────────────────────
if [ ! -f "$SECRETS" ]; then
  if [ -f "$OUT" ] && grep -q '^JWT_SECRET=' "$OUT"; then
    echo "Migrating secrets from legacy $OUT -> $SECRETS"
    {
      echo "# Migrated from $OUT on $NOW — auto-generated secrets, gitignored, mode 600."
      for k in $SECRET_KEYS; do grep -m1 "^${k}=" "$OUT" || true; done
    } >"$SECRETS"
    chmod 600 "$SECRETS"
  else
    bash scripts/env/generate-env.sh "$SECRETS"
  fi
fi

# ── 2. optional local layer ──────────────────────────────────────────────────
if [ ! -f "$LOCAL" ]; then
  {
    echo "# .env.local — optional API keys + per-developer overrides (gitignored)."
    echo "# See .env.local.example. Appended last, so it overrides config/secrets."
    if [ -f "$OUT" ]; then
      for k in $OPTIONAL_KEYS; do
        v="$(grep -m1 "^${k}=" "$OUT" 2>/dev/null || true)"
        [ -n "$v" ] && [ "$v" != "${k}=" ] && echo "$v" # carry over only non-empty
      done
    fi
  } >"$LOCAL"
  chmod 600 "$LOCAL"
fi

# ── GitHub tokens never enter .env ──────────────────────────────────────────
# .env is handed to every container (`env_file: [.env]` in the plane files,
# vendor playground apps included), and every `make env` re-injects it. A PAT
# pasted into .env.local therefore reached the whole stack (found 2026-09-21).
# The only consumer of a GitHub token in this repo runs on the HOST
# (scripts/vault/vault-session.mjs) and reads ~/.grobase-gh-pat, mode 600.
# A token-shaped line is withheld here and named on stderr; the rest of
# .env.local is legitimate, so assembly still succeeds. Matched by key name
# or by value shape (ghp_/gho_/ghu_/ghs_/ghr_ classic, github_pat_ fine-grained).
GH_TOKEN_KEYS='GITHUB_TOKEN|GH_TOKEN|GH_PAT|VAULT_GITHUB_TOKEN|GHCR_TOKEN|CR_PAT'
GH_TOKEN_SHAPE='gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}'
local_layer() {
  local line key val
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
    '#'* | '')
      printf '%s\n' "$line"
      continue
      ;;
    esac
    key="${line%%=*}"
    val="${line#*=}"
    if printf '%s' "$key" | grep -qE "^(${GH_TOKEN_KEYS})$" ||
      printf '%s' "$val" | grep -qE "^[\"']?(${GH_TOKEN_SHAPE})"; then
      echo "WARNING: $LOCAL: $key looks like a GitHub token -- withheld from $OUT (every container reads it). Keep it in ~/.grobase-gh-pat (mode 600) and rotate the one that was here." >&2
      printf '# %s= (GitHub token withheld by assemble-env.sh; see ~/.grobase-gh-pat)\n' "$key"
      continue
    fi
    printf '%s\n' "$line"
  done <"$LOCAL"
}

# ── 3. assemble (config < secrets < local; duplicate keys: later wins) ────────
{
  echo "# ASSEMBLED by 'make env' on $NOW — DO NOT EDIT THIS FILE."
  echo "# Edit the sources then re-run 'make env':"
  echo "#   config.env (committed) · .env.secrets (generated) · .env.local (yours)"
  echo
  echo "# ========== config.env =========="
  cat "$CONFIG"
  echo
  echo "# ========== .env.secrets =========="
  cat "$SECRETS"
  echo
  echo "# ========== .env.local =========="
  local_layer
} >"$OUT"
chmod 600 "$OUT"
echo "Assembled $OUT  (config.env + .env.secrets + .env.local)"
