#!/bin/sh
# render-example.sh - render .env.example from infra/config/env/schema.json.
#
# The schema is the authority; .env.example is a generated view of it. This script
# reads no .env, .env.secrets or .env.local, so no secret value can reach its output.
#
# Ponytail: rendering is a plain projection of the schema, so it is exact for what the
# schema states and silent about what it omits. `consumers[]` is deliberately not
# rendered (compose evidence, 10+ names per key, churns); read it from schema.json.
# Placeholders follow the schema only: `default`, else CHANGE_ME if required in any
# environment, else empty. A key required in only one environment still gets CHANGE_ME.
set -eu

usage() {
  cat <<'EOF'
Usage: render-example.sh [--write | --check | -h | --help]

Render .env.example from infra/config/env/schema.json (needs jq).

  (no flag)   print the rendered file to stdout, write nothing
  --write     overwrite .env.example with the rendered file
  --check     diff .env.example against the rendered file, write nothing
  -h, --help  print this help and exit 0

Exit codes:
  0  success (--check: .env.example is in sync with the schema)
  1  --check found drift or a missing .env.example (a diff is printed)
  2  bad usage (unknown flag, or more than one argument)
  3  jq or infra/config/env/schema.json is missing, or the schema cannot be rendered
EOF
}

die() {
  printf 'render-example: %s\n' "$2" >&2
  exit "$1"
}

repo_root() {
  cd "$(dirname "$0")/../.." && pwd
}

preflight() {
  command -v jq >/dev/null 2>&1 || die 3 "jq is required (not found on PATH)"
  [ -f "$1" ] || die 3 "schema not found: $1"
}

render_header() {
  render_header_intro
  render_header_layers
}

render_header_intro() {
  cat <<'EOF'
# ==========================================================================
# .env.example - GENERATED from infra/config/env/schema.json. Do not edit.
#
#   regenerate:  bash scripts/env/render-example.sh --write
#   verify:      make env-example-check      (exits 1 when this file drifted)
#
# This is a schema document, not a file to copy: it lists every key the
# platform classifies, who may know its value, and where that value lives.
#
EOF
}

render_header_layers() {
  cat <<'EOF'
# Configuration is three layers. A later layer overrides an earlier one, and
# `make env` assembles them into .env (rebuilt every time, never edit it):
#
#   config.env  <  .env.secrets  <  .env.local   ->   .env
#
#   config.env    committed. Non-secret config: hosts, URLs, names, tuning.
#   .env.secrets  generated by `make env`, gitignored, mode 600. The minted
#                 secrets. Source of truth for a SECRET is vault42.
#   .env.local    optional, gitignored. Per-developer overrides and the
#                 external keys (OAuth, LLM, SMTP). Template: .env.local.example.
#
# Placeholders: CHANGE_ME = required, you must supply it. Empty = optional.
# A commented-out key is derived; it is rebuilt, never set by hand. No real
# value belongs in this file (gate m214 refuses one).
# ==========================================================================
EOF
}

jq_defs_meta() {
  cat <<'EOF'
def parts: [match("\\$\\{([A-Z_0-9]+)\\}"; "g").captures[0].string] | unique;
def req($envs):
  (.required_in // []) as $r
  | if ($r | length) == 0 then "optional"
    elif ($r | length) == ($envs | length) then "required in all environments"
    else "required in " + ($r | join(",")) end;
def fmt:
  if .derived_from then "derived"
  elif .format == "enum" then "format enum(" + (.allowed | join("|")) + ")"
  elif .format then "format " + .format
  else "format unspecified" end;
def meta($envs):
  [ .category, req($envs), fmt,
    (if .vault42_path then "vault42 " + .vault42_path else empty end),
    (if .compose_required then "compose-required" else empty end),
    (if .browser_safe then "browser-safe" else empty end) ]
  | join(" | ");
EOF
}

jq_defs_entry() {
  cat <<'EOF'
def check:
  if .value.category == "SECRET" and .value.vault42_path == null and .value.derived_from == null
  then error(.key + ": SECRET with neither vault42_path nor derived_from") else . end;
def placeholder:
  if .value.default != null then (.value.default | tostring)
  elif (.value.required_in // [] | length) > 0 then "CHANGE_ME"
  else "" end;
def derived_note:
  "# Derived, not stored in vault42: "
  + (.value.built_by // "built from its parts")
  + " builds it from " + (.value.derived_from | parts | join(", ")) + ".";
def entry($envs):
  "# " + (.value | meta($envs)),
  (if .value.derived_from then derived_note, "# " + .key + "="
   else .key + "=" + placeholder end);
def none($cat):
  "# No key is classified " + $cat + " in schema.json."
  + (if $cat == "CONFIG" then " A key absent from the schema defaults to CONFIG and lives in config.env." else "" end);
EOF
}

jq_main() {
  cat <<'EOF'
def section($cat; $desc; $envs; $all):
  ($all | map(select(.value.category == $cat)) | sort_by([(.value.derived_from != null), .key])) as $keys
  | "", "# " + ("=" * 74), "# " + $cat + ": " + $desc, "# " + ("=" * 74),
    (if ($keys | length) == 0 then "", none($cat) else $keys[] | "", entry($envs) end);
. as $s
| $s.environments as $envs
| ["ENVIRONMENT", "CONFIG", "PUBLIC", "SECRET"] as $order
| ($s.keys | to_entries | map(check)) as $all
| ($all | map(.value.category) | unique - $order) as $stray
| if ($stray | length) > 0 then error("category with no section: " + ($stray | join(","))) else . end
| "# Environments: " + ($envs | join(", ")),
  "# vault42 home: " + $s.vault42.org + "/" + $s.vault42.project + ", a SECRET lives at " + $s.vault42.path,
  ($order[] as $cat | section($cat; $s.categories[$cat]; $envs; $all))
EOF
}

render() {
  render_header
  printf '\n'
  jq -r "$(jq_defs_meta; jq_defs_entry; jq_main)" "$1"
}

run_print() {
  schema=$1/infra/config/env/schema.json
  preflight "$schema"
  render "$schema" || die 3 "schema is not renderable: $schema"
}

run_write() {
  schema=$1/infra/config/env/schema.json
  preflight "$schema"
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' EXIT
  render "$schema" >"$tmp" || die 3 "schema is not renderable: $schema"
  cat "$tmp" >"$1/.env.example"
  printf 'render-example: wrote .env.example\n' >&2
}

run_check() {
  schema=$1/infra/config/env/schema.json
  preflight "$schema"
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' EXIT
  render "$schema" >"$tmp" || die 3 "schema is not renderable: $schema"
  [ -f "$1/.env.example" ] || die 1 ".env.example is missing; run: bash scripts/env/render-example.sh --write"
  diff -u "$1/.env.example" "$tmp" && return 0
  printf 'render-example: .env.example has drifted from the schema; run: bash scripts/env/render-example.sh --write\n' >&2
  return 1
}

main() {
  case "$#:${1-}" in
  0:) run_print "$(repo_root)" ;;
  1:--write) run_write "$(repo_root)" ;;
  1:--check) run_check "$(repo_root)" ;;
  1:-h | 1:--help) usage ;;
  *)
    usage >&2
    exit 2
    ;;
  esac
}

main "$@"
