#!/usr/bin/env bash
# **************************************************************************** #
#                                                                              #
#  image-provenance.sh — stamp every image built from this tree with the       #
#  commit it came from, and refuse to start one that is older than its source  #
#                                                                              #
#  WHY                                                                         #
#    grobase-realtime:latest once lagged the commit being configured: the      #
#    stack ran a binary that ignored the origin list it was handed, and        #
#    nothing could tell, because no image said which commit it was built       #
#    from (issue #19). A deployment has to be able to prove, per image, that   #
#    the binary corresponds to the source it is configured against.           #
#                                                                              #
#  HOW                                                                         #
#    override  prints a compose override that labels every service with a     #
#              `build:` context:                                               #
#                org.opencontainers.image.revision = <HEAD sha>[-dirty]        #
#                org.grobase.build.context         = <context path>            #
#              `-dirty` when that context has uncommitted changes. `make       #
#              build` passes it with a second -f, so no service definition     #
#              carries the label and none can be forgotten.                    #
#    check     reads the resolved compose config (JSON on stdin) and, for      #
#              every buildable service whose image exists locally, compares    #
#              the image's revision with the LAST commit that touched its      #
#              build context. The image is                                    #
#                ok        its revision contains that commit                   #
#                STALE     built before its source last changed -> exit 1      #
#                dirty     built from uncommitted changes (reported)           #
#                unproven  no revision label, e.g. pulled from a registry      #
#                          (reported: missing evidence is not a mismatch)      #
#              Comparing with the context's last change, not with HEAD, keeps  #
#              an unrelated commit from invalidating every image.              #
#              GROBASE_ALLOW_STALE_IMAGES=1 downgrades STALE to a warning.     #
#                                                                              #
#  USAGE                                                                       #
#    image-provenance.sh override <compose-config.json>  > override.yml        #
#    docker compose config --format json | image-provenance.sh check           #
#    GROBASE_PROVENANCE_REPO=<dir>  the git tree to read (default: repo root)  #
#                                                                              #
#  Proven by scripts/verify/m190-image-provenance.sh.                          #
# **************************************************************************** #
set -euo pipefail
ROOT="${GROBASE_PROVENANCE_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
LABEL_REV=org.opencontainers.image.revision
LABEL_CTX=org.grobase.build.context

die() {
  echo "image-provenance: $*" >&2
  exit 2
}
command -v python3 >/dev/null 2>&1 || die "python3 is required"
is_git() { git -C "$ROOT" rev-parse --git-dir >/dev/null 2>&1; }

# service <TAB> image <TAB> context-relative-to-ROOT, one line per buildable service
buildable() { # <config.json>
  python3 - "$1" "$ROOT" <<'PY'
import json, os, sys
cfg, root = json.load(open(sys.argv[1])), os.path.realpath(sys.argv[2])
for name, svc in sorted((cfg.get("services") or {}).items()):
    b = svc.get("build")
    if not b:
        continue
    ctx = b if isinstance(b, str) else b.get("context", "")
    if not ctx or "://" in ctx:
        continue
    ctx = os.path.relpath(os.path.realpath(ctx if os.path.isabs(ctx) else os.path.join(root, ctx)), root)
    image = svc.get("image") or f'{cfg.get("name", "")}-{name}'
    print(f"{name}\t{image}\t{ctx}")
PY
}

cmd_override() {
  local cfg="$1" head svc image ctx rev
  is_git || die "$ROOT is not a git work tree: nothing to stamp images with"
  head=$(git -C "$ROOT" rev-parse HEAD)
  echo "# generated by scripts/ops/image-provenance.sh override -- do not commit"
  echo "services:"
  while IFS=$'\t' read -r svc image ctx; do
    rev="$head"
    [ -z "$(git -C "$ROOT" status --porcelain -- "$ctx" 2>/dev/null)" ] || rev="${head}-dirty"
    printf '  %s:\n    build:\n      labels:\n        %s: "%s"\n        %s: "%s"\n' \
      "$svc" "$LABEL_REV" "$rev" "$LABEL_CTX" "$ctx"
  done < <(buildable "$cfg")
}

cmd_check() {
  local cfg svc image ctx rev last base stale=0 n=0 ok=0 unproven=0 dirty=0
  # A tarball install has no history to compare with: say so, do not block.
  if ! is_git; then
    cat >/dev/null
    echo "image-provenance: not checked ($ROOT is not a git work tree)"
    return 0
  fi
  cfg=$(mktemp)
  trap 'rm -f "$cfg"' RETURN
  cat >"$cfg"
  while IFS=$'\t' read -r svc image ctx; do
    docker image inspect "$image" >/dev/null 2>&1 || continue
    n=$((n + 1))
    rev=$(docker image inspect -f "{{index .Config.Labels \"$LABEL_REV\"}}" "$image" 2>/dev/null || true)
    last=$(git -C "$ROOT" log -1 --format=%H -- "$ctx" 2>/dev/null || true)
    if [ -z "$rev" ] || [ "$rev" = "<no value>" ]; then
      unproven=$((unproven + 1))
      printf '  unproven  %-28s %s (no %s label)\n' "$svc" "$image" "$LABEL_REV"
      continue
    fi
    base="${rev%-dirty}"
    if [ -z "$last" ]; then
      ok=$((ok + 1))
    elif ! git -C "$ROOT" cat-file -e "${base}^{commit}" 2>/dev/null; then
      unproven=$((unproven + 1))
      printf '  unproven  %-28s built from %s, a commit this clone does not have\n' "$svc" "${rev:0:12}"
    elif git -C "$ROOT" merge-base --is-ancestor "$last" "$base"; then
      if [ "$base" != "$rev" ]; then
        dirty=$((dirty + 1))
        printf '  dirty     %-28s built from uncommitted changes on %s\n' "$svc" "${base:0:12}"
      else
        ok=$((ok + 1))
      fi
    else
      stale=$((stale + 1))
      printf '  STALE     %-28s built from %s, but %s last changed in %s — rebuild it (make build-svc-%s)\n' \
        "$svc" "${base:0:12}" "$ctx" "${last:0:12}" "$svc"
    fi
  done < <(buildable "$cfg")
  echo "image-provenance: ${n} local image(s): ${ok} ok, ${stale} stale, ${dirty} dirty, ${unproven} unproven"
  if [ "$stale" -gt 0 ]; then
    if [ "${GROBASE_ALLOW_STALE_IMAGES:-0}" = 1 ]; then
      echo "image-provenance: GROBASE_ALLOW_STALE_IMAGES=1 — starting anyway" >&2
      return 0
    fi
    echo "image-provenance: refusing to start ${stale} image(s) older than their source (GROBASE_ALLOW_STALE_IMAGES=1 to override)" >&2
    return 1
  fi
}

case "${1:-}" in
override)
  [ $# -eq 2 ] || die "usage: image-provenance.sh override <compose-config.json>"
  cmd_override "$2"
  ;;
check) cmd_check ;;
*) die "usage: image-provenance.sh override <config.json> | check < config.json" ;;
esac
