//
// AuthSignUp200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AuthSignUp200Response: Codable, JSONEncodable, Hashable {
    case typeSession(Session)
    case typeUser(User)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeSession(let value):
            try container.encode(value)
        case .typeUser(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(Session.self) {
            self = .typeSession(value)
        } else if let value = try? container.decode(User.self) {
            self = .typeUser(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of AuthSignUp200Response"))
        }
    }
}


// NOTE: AuthSignUp200Response is a oneOf enum with no `id` property, so it cannot
// conform to Identifiable — the generator's extension was a compile error on Swift 6.
