-- agency-normalize-ids.sql — make every integer primary key auto-generating.
--
-- The agency tables are created via the DDL create_table path (and the edges
-- table inline), which renders the `id` PK as a plain `bigint`/`integer` with no
-- sequence/identity. The osionos live-database block inserts rows WITHOUT an id
-- (it expects the engine to generate one), so a plain PK rejects the NULL id and
-- the insert 409s ("null value in column id violates not-null constraint").
--
-- This converts each integer `id` PK to GENERATED BY DEFAULT AS IDENTITY (BY
-- DEFAULT, not ALWAYS, so the seed's explicit-id inserts still work) and syncs
-- the identity sequence past the current max. It is idempotent (skips columns
-- already identity/defaulted) and additive (no data is touched), so it is safe
-- to run on every (re)provision. MUST run AFTER the row data is loaded — the
-- sequence is synced from max(id), and explicit-id inserts do not advance it.
DO $$
DECLARE
  r RECORD;
  nextid BIGINT;
BEGIN
  FOR r IN
    SELECT c.relname AS tbl
    FROM pg_class c
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attname = 'id' AND NOT a.attisdropped
    JOIN pg_type ty ON ty.oid = a.atttypid
    JOIN information_schema.columns col
      ON col.table_schema = 'public' AND col.table_name = c.relname AND col.column_name = 'id'
    WHERE c.relkind = 'r'
      AND c.relnamespace = 'public'::regnamespace
      AND ty.typname IN ('int2', 'int4', 'int8')
      AND col.is_identity = 'NO'
      AND col.column_default IS NULL
    ORDER BY c.relname
  LOOP
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', r.tbl);
    EXECUTE format('SELECT COALESCE(MAX(id), 0) + 1 FROM public.%I', r.tbl) INTO nextid;
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id RESTART WITH %s', r.tbl, nextid);
    RAISE NOTICE 'normalized %  -> next id = %', r.tbl, nextid;
  END LOOP;
END $$;

-- Relax every NOT NULL column that has no default and is not part of the
-- primary key (and is not the server-controlled owner_id). osionos's live
-- database adds a BLANK row first and fills cells after, so a required column
-- with no default rejects that insert ("null value in column … violates
-- not-null"). DROP NOT NULL makes the column optional without touching existing
-- data; full-row inserts (seed / simulations) are unaffected, and any unique
-- constraint still holds for non-null values.
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT c.relname AS tbl, a.attname AS col
    FROM pg_class c
    JOIN pg_namespace ns ON ns.oid = c.relnamespace AND ns.nspname = 'public'
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
    WHERE c.relkind = 'r'
      AND a.attnotnull
      AND NOT a.atthasdef
      AND a.attidentity = ''
      AND a.attname <> 'owner_id'
      AND NOT EXISTS (
        SELECT 1 FROM pg_index i
        WHERE i.indrelid = c.oid AND i.indisprimary AND a.attnum = ANY (i.indkey)
      )
  LOOP
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I DROP NOT NULL', r.tbl, r.col);
  END LOOP;
END $$;
